//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "hashtag")]
pub struct Model {
    pub hashtag: Option<String>,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub value: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::post_hashtag::Entity")]
    PostHashtag,
}

impl Related<super::post_hashtag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PostHashtag.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
