//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

pub use super::admin::Entity as Admin;
pub use super::admin_access::Entity as AdminAccess;
pub use super::device::Entity as Device;
pub use super::system_access::Entity as SystemAccess;
pub use super::user_credential::Entity as UserCredential;
pub use super::user_login::Entity as UserLogin;
pub use super::user_profile::Entity as UserProfile;
pub use super::user_report::Entity as UserReport;
pub use super::user_verification::Entity as UserVerification;
