//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

pub use super::admin::Entity as Admin;
pub use super::admin_role::Entity as AdminRole;
pub use super::attachment::Entity as Attachment;
pub use super::post::Entity as Post;
pub use super::system_access::Entity as SystemAccess;
pub use super::user_credential::Entity as UserCredential;
pub use super::user_log::Entity as UserLog;
pub use super::user_profile::Entity as UserProfile;
