//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "auth_provider")]
pub enum AuthProvider {
    #[sea_orm(string_value = "APPLE")]
    Apple,
    #[sea_orm(string_value = "BASIC")]
    Basic,
    #[sea_orm(string_value = "FACEBOOK")]
    Facebook,
    #[sea_orm(string_value = "GITHUB")]
    Github,
    #[sea_orm(string_value = "GOOGLE")]
    Google,
    #[sea_orm(string_value = "MICROSOFT")]
    Microsoft,
    #[sea_orm(string_value = "TWITTER")]
    Twitter,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "status")]
pub enum Status {
    #[sea_orm(string_value = "ACTIVE")]
    Active,
    #[sea_orm(string_value = "INACTIVE")]
    Inactive,
    #[sea_orm(string_value = "SUSPENDED")]
    Suspended,
    #[sea_orm(string_value = "WAITING_CONFIRMATION")]
    WaitingConfirmation,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "verification_type")]
pub enum VerificationType {
    #[sea_orm(string_value = "ACTIVATION")]
    Activation,
    #[sea_orm(string_value = "OTP")]
    Otp,
    #[sea_orm(string_value = "RESET")]
    Reset,
}
