#!/bin/sh
#
# This hook is for Android project git repos.
#
# You can use git config variables to customize this hook.
# -----------------------------------------------------------
# Change hooks.lintTargetDirectory to point at a non . directory
# Change hooks.lintArgs to add any custom lint arguments you prefer

# Get custom info
dirToLint=$(git config hooks.lintTargetDirectory)
lintArgs=$(git config hooks.lintArgs)
projectDir=$(git rev-parse --show-toplevel)
lintReportPath="/lint-report.html"

# If user has not defined a preferred directory to lint against, make it .
if [ -z "$dirToLint"]
  then
  dirToLint="."
fi

# Perform lint check
echo "Performing pre-push lint check of ""$dirToLint"
./gradlew checkstyleMain --daemon
detektStatus=$?

lintStatus=1
if [ $detektStatus -eq 0 ]
then
  echo "Rest Checkstyle Success."
  lintStatus=$?

  if [ $lintStatus -ne 0 ]
  then
    echo "Rest Lint failure, git push aborted."
    echo "Open ${projectDir}${lintReportPath} in a browser to see Lint Report"
    exit 1
  fi
else
  echo "Rest Checkstyle failure, git push aborted."
  exit 1
fi

echo "LintStatus ${lintStatus}"
echo "CheckstyleStatus ${detektStatus}"

exit $lintStatus